batch_size: 128 #2048
/num_workers: 1
# shuffle: True
/persistent_workers: False
/pin_memory: False
multiprocessing_context: fork #if on MPS you get RuntimeError: _share_filename_: only available on CPU